DeXinYuan/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeXinYuan.Models
{
    public class Product
    {
        public int Id { get; set; }

        public string ProductName { get; set; }

        public int CategoryId { get; set; }

        public string ProductRemark { get; set; }

        public string ImgUrl { get; set; }

        public bool IsDel { get; set; }
    }

    public class Category
    {
        public int Id { get; set; }

        public string CategoryName { get; set; }

        public int Pid { get; set; }

        public bool IsDel { get; set; }
    }
}

DeXinYuan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeXinYuan.Models;

namespace DeXinYuan.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DeXinYuan/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeXinYuan.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewsDetail()
        {
            return View();
        }
    }
}

DeXinYuan/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeXinYuan.Models;

namespace DeXinYuan.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index(int categoryId=0)
        {
            var list = SqlHelper.Query<Category>("select * from Category where IsDel=0").ToList();

            var pList = SqlHelper.Query<Product>("select * from Product where IsDel=0 and CategoryId=@CategoryId", new { categoryId= categoryId==0?list[0].Id: categoryId }).ToList();

            ViewBag.categoryId = categoryId == 0 ? list[0].Id : categoryId;
            ViewBag.products = pList;
            return View(list);
        }

        public ActionResult Detail(int id)
        {
            return View();
        }
    }
}

DeXinYuan/Controllers/ProjectController.cs
using DeXinYuan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeXinYuan.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {
            var list = SqlHelper.Query<Category>("select * from Category where IsDel=0").ToList();

            var pList = SqlHelper.Query<Product>("select * from Product where IsDel=0 and CategoryId=@CategoryId", new { categoryId = 1}).ToList();

            ViewBag.products = pList;
            return View(list);
        }
    }
}

DeXinYuan/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    ViewBag.active = "Home/About";
}
<div class="bread_bg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="bread_nav">
                    <span>您的位置：</span><a href="../../index.htm" tppabs="http://demo.weboss.hk/h127/">首 页</a> &gt;
                    <a href="index.htm" tppabs="http://demo.weboss.hk/h127/page/html">关于我们</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">

        <!-- right -->
        <div class="col-xs-12 col-sm-8 col-md-9" style="float:right">
            <div class="right_head">
                <h2><span> 公司简介</span></h2>
            </div>
            <div class="right_contents">
                <p>
                    河北宸轩雕塑工艺品制造有限公司成立于2000年，地理位置优越，位于古时“尧帝故里奉国之城-河北唐县”，是一家专业生产销售城市雕塑、景观雕塑、铜佛像的厂家。主要产品有：城市雕塑、公司形象雕塑、园林景观雕塑、铜佛像、铜钟和铁钟、香炉塔炉佛教用品等；中心一贯坚持“质量第一，用户至上，优质服务，信守合同”的宗旨，凭借着高质量的产品，良好的信誉，优质的服务，产品畅销全国近三十多个省、市、自治区以及远销欧美、西亚等国家。竭诚与国内外商界宗教界合作，共同发展，共创辉煌！
                </p>
                
                <p>
                    本中心声明：为了宗教界更快更好的发展，响应国家政策，寺院工程及用品一律优惠！欢迎宗教界朋友来来图来样加工订做，期待你的光临指导！
                </p>
                <p>
                    宸轩铜雕的铸造方法有：精密铸造硅溶胶铸造、施蜡铸造、树脂砂铸造、锻铜制造、整体铸造、分体铸造等是国内一流的铸造技术。

                    宸轩人的精神：塑一尊佛像、结佛缘、相好庄严、心欢喜欢，镏一镂黄金、积累宿世功德。用心塑造佛像、望佛悲悯加护、得以往生极乐！园无铜雕不秀，宝无铜雕不雅。涵天地之精华，缩山川之美妙。亘古日月放异彩，精雕为友品自洁。巧雕不语亦有情，怡神冶性是精灵。攻措生光，精描璀璨，雕琢成器，巧制玲珑。铜为浓缩的天体，雕为可收藏的大自然。表里俱佳丝丝入扣，形神兼备栩栩如生。我们从事的乃实在之大业，不朽之盛世。玉不琢，不成器，精诚所至，金石为开。经典是因为继承传统；一流是因为出自大师；坚定是因为脚踏实地；出色是因为点铜成金，我们将赋予它永恒的“生命”和灵性，您提供一张图纸或图片，我们将用铜雕塑阐释它的生动形象与精神内涵，我们将与您共同创造不朽的诗篇，凝固的音乐。追求完美，止于至善—是我们的企业文化。
                    我们生产雕塑：1、有详尽的计划。2、辛勤的工作。3、严格的纪律。4、对细微之处的专注。做到精益求精，精雕细琢，一丝不苟—这就是宸轩人的精神！宸轩铜雕以“质量第一，信誉可靠”的发展目标欢迎广大客户的光临。
                </p>
            </div>
        </div>

        <!-- left -->
        <div class="col-xs-12 col-sm-4 col-md-3">
            <h3 class="left_h3"><span>导航栏目</span></h3>
            <div class="left_column">

                <ul class="left_nav_ul" id="firstpane">

                    <li>
                        <a class="biglink" href="about.php.htm" tppabs="http://demo.weboss.hk/h127/page/html/about.php">公司简介</a>
                        <ul class="left_snav_ul menu_body"></ul>
                    </li>

                    <li>
                        <a class="biglink" href="contact.php.htm" tppabs="http://demo.weboss.hk/h127/page/html/contact.php">联系我们</a>
                        <ul class="left_snav_ul menu_body"></ul>
                    </li>

                    <li>
                        <a class="biglink" href="feedback.php.htm" tppabs="http://demo.weboss.hk/h127/page/html/feedback.php">留言反馈</a>
                        <ul class="left_snav_ul menu_body"></ul>
                    </li>

                    <li>
                        <a class="biglink" href="services.php.htm" tppabs="http://demo.weboss.hk/h127/page/html/services.php">我们的服务</a>
                        <ul class="left_snav_ul menu_body"></ul>
                    </li>

                </ul>
            </div>
            <div class="left_news">
                <h3 class="left_h3"><span>新闻中心</span></h3>

                <ul class="left_news">

                    <li>
                        <a href="../../news/html/-431.html" tppabs="http://demo.weboss.hk/h127/news/html/?431.html"
                           title="如何解决光扩散PC注塑成型">如何解决光扩散PC注塑成型</a>
                    </li>

                    <li>
                        <a href="../../news/html/-430.html" tppabs="http://demo.weboss.hk/h127/news/html/?430.html"
                           title="充电器外壳阻燃防火PC 充">充电器外壳阻燃防火PC 充</a>
                    </li>

                    <li>
                        <a href="../../news/html/-429.html" tppabs="http://demo.weboss.hk/h127/news/html/?429.html"
                           title="如何解决导电PC注塑件熔接">如何解决导电PC注塑件熔接</a>
                    </li>

                    <li>
                        <a href="../../news/html/-428.html" tppabs="http://demo.weboss.hk/h127/news/html/?428.html"
                           title="HTML5提供了一些新的元素">HTML5提供了一些新的元素</a>
                    </li>

                </ul>

            </div>
            <div class="left_contact">
                <h3 class="left_h3" style="margin-bottom:20px;"><span>联系我们</span></h3>
                <p>
                    联系人：吴先生
                </p>
                <p>
                    手机：18926129998
                </p>
                <p>
                    电话：020-22043297
                </p>
                <p>
                    邮箱：510551@qq.com
                </p>
                <p>
                    地址： 广东省广州市天河区天平架沙太路沙太路
                </p>
            </div>
        </div>

    </div>
</div>
<script src="/content/js/jquery.smoove.min.js"></script>
<script>$('.product_head,.product_img,.left_nav,.case_head,.case_img,.advantage_head,.advantage_right,.advantage_left,.news_head,.news_ul,.answer_ul,.about_head,.js_about_left,.js_about_right,.cooperation_head,.cooperation_img').smoove({ offset: '10%' });</script>

DeXinYuan/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DeXinYuan/Views/News/Index.cshtml
@{
    ViewBag.active = "Product/News";
    ViewBag.Title = "News";
}

<div class="bread_bg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="bread_nav">
                    <span>您的位置：</span><a href="" tppabs="http://demo.weboss.hk/h127/">首 页</a> &gt;
                    <a href="" tppabs="http://demo.weboss.hk/h127/page/html">新闻中心</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">

        <!-- right -->
        <div class="col-xs-12 col-sm-8 col-md-9" style="float:right">

            <div class="right_head">
                <h2><span>公司新闻</span></h2>
            </div>
            <ul class="right_new">

                <li>
                    <a href="../html/-404.html" tppabs="http://demo.weboss.hk/h127/news/html/?404.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-413.html" tppabs="http://demo.weboss.hk/h127/news/html/?413.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-392.html" tppabs="http://demo.weboss.hk/h127/news/html/?392.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-414.html" tppabs="http://demo.weboss.hk/h127/news/html/?414.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-415.html" tppabs="http://demo.weboss.hk/h127/news/html/?415.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-416.html" tppabs="http://demo.weboss.hk/h127/news/html/?416.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-417.html" tppabs="http://demo.weboss.hk/h127/news/html/?417.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-418.html" tppabs="http://demo.weboss.hk/h127/news/html/?418.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-419.html" tppabs="http://demo.weboss.hk/h127/news/html/?419.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

                <li>
                    <a href="../html/-420.html" tppabs="http://demo.weboss.hk/h127/news/html/?420.html" title="HTML5提供了一些新的元素和属性
">
                        HTML5提供了一些新的元素和属性
                    </a><span class="news_time">2010-01-25</span>
                </li>

            </ul>
            <div class="page">
                <span class="current">1</span><a href="index.php-page=2&catid=86&myord=dtime&myshownums=&showtj=&showdate=&author=&key=.htm"
                                                 tppabs="http://demo.weboss.hk/h127/news/class/index.php?page=2&catid=86&myord=dtime&myshownums=&showtj=&showdate=&author=&key=">2</a><a href="index.php-page=2&catid=86&myord=dtime&myshownums=&showtj=&showdate=&author=&key=.htm"
                                                                                                                                                                                         tppabs="http://demo.weboss.hk/h127/news/class/index.php?page=2&catid=86&myord=dtime&myshownums=&showtj=&showdate=&author=&key=">&raquo;</a>
                </ul>
            </div>

        </div>

        <!-- left -->
        <div class="col-xs-12 col-sm-4 col-md-3">
            <h3 class="left_h3"><span>导航栏目</span></h3>
            <div class="left_column">
                <ul class="left_nav_ul" id="firstpane">

                    <li>
                        <a class="biglink" href="-86.html"
                           tppabs="http://demo.weboss.hk/h127/news/class/?86.html">公司新闻</a>
                    </li>
                    <ul class="left_snav_ul">

                        <li>
                            <a href="-102.html" tppabs="http://demo.weboss.hk/h127/news/class/?102.html"
                               target="_self">部门新闻</a>
                        </li>

                    </ul>

                    <li>
                        <a class="biglink" href="-99.html"
                           tppabs="http://demo.weboss.hk/h127/news/class/?99.html">行业新闻</a>
                    </li>
                    <ul class="left_snav_ul"></ul>

                    <li>
                        <a class="biglink" href="-106.html"
                           tppabs="http://demo.weboss.hk/h127/news/class/?106.html">常见问题</a>
                    </li>
                    <ul class="left_snav_ul"></ul>

                </ul>
            </div>
            <div class="left_news">
                <h3 class="left_h3"><span>新闻中心</span></h3>

                <ul class="left_news">

                    <li>
                        <a href="../html/-431.html" tppabs="http://demo.weboss.hk/h127/news/html/?431.html"
                           title="如何解决光扩散PC注塑成型">如何解决光扩散PC注塑成型</a>
                    </li>

                    <li>
                        <a href="../html/-430.html" tppabs="http://demo.weboss.hk/h127/news/html/?430.html"
                           title="充电器外壳阻燃防火PC 充">充电器外壳阻燃防火PC 充</a>
                    </li>

                    <li>
                        <a href="../html/-429.html" tppabs="http://demo.weboss.hk/h127/news/html/?429.html"
                           title="如何解决导电PC注塑件熔接">如何解决导电PC注塑件熔接</a>
                    </li>

                    <li>
                        <a href="../html/-428.html" tppabs="http://demo.weboss.hk/h127/news/html/?428.html"
                           title="HTML5提供了一些新的元素">HTML5提供了一些新的元素</a>
                    </li>

                </ul>

            </div>
            <div class="left_contact">
                <h3 class="left_h3" style="margin-bottom:20px;"><span>联系我们</span></h3>
                <p>
                    联系人：吴先生
                </p>
                <p>
                    手机：18926129998
                </p>
                <p>
                    电话：020-22043297
                </p>
                <p>
                    邮箱：510551@qq.com
                </p>
                <p>
                    地址： 广东省广州市天河区天平架沙太路沙太路
                </p>
            </div>
        </div>

    </div>
</div>

DeXinYuan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>河北宸轩雕塑</title>
    <meta name="keywords" content="keywords" />
    <meta name="description" content="memomemomemomemomemo" />
    <meta name="applicable-device" content="pc,mobile" />
    <link href="/content/css/bootstrap.css" rel="stylesheet" />
    <link href="/content/css/bxslider.css" rel="stylesheet" />
    <link href="/content/css/style.css" rel="stylesheet" />
    <script src="/content/js/jquery.min.js"></script>
    <script src="/content/js/bxslider.min.js"></script>
    <script src="/content/js/common.js"></script>
    <script src="/content/js/bootstrap.js"></script>


    <!--[if lt IE 9]>
      <script src="../../cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js" tppabs="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="../../cdn.bootcss.com/respond.js/1.4.2/respond.min.js" tppabs="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <header>
        <!--顶部-->
        <div class="top_bg">
            <div class="container">
                <div class="col-xs-12 col-sm-9 col-md-9">
                    <span class="top_welcome">欢迎光临河北宸轩雕塑网</span>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3">
                    <form id="searchform" method="get" action="">
                        <div class="input-group search_group">
                            <input type="text" name="key" class="form-control input-sm" placeholder="产品搜索">
                            <span class="input-group-btn">
                                <span id="search_submit" onclick="searchform.submit();" title="产品搜索"
                                      class="glyphicon glyphicon-search btn-lg" aria-hidden="true"></span>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!--banner-->
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-9 col-md-9">
                    <a href="#"><img src="/content/images/logo.png" class="logo" /></a>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 tel_box">
                    <div class="top_tel">
                        <img src="/content/images/tel.png" alt="服务热线">
                        <span>全国服务热线：</span>
                        <p>136-9928-5614</p>
                    </div>
                </div>
            </div>
        </div>

        <!--菜单-->
        <nav id="top_nav" class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">导航菜单</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span id="search_btn" class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    <a class="navbar-brand" href="#">导航菜单</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li><a href="@Url.Action("Index","Home")">首 页</a></li>

                        <li><a href="@Url.Action("About","Home")">关于我们</a></li>

                        <li><a href="@Url.Action("Index","Product")">产品展示</a></li>

                        <li><a href="@Url.Action("Index","Project")">工程案例</a></li>

                        <li><a href="@Url.Action("Index","News")">新闻资讯</a></li>

                        <li><a href="page/html/contact.php.htm">联系我们</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3">
                    <img class="footer_logo" src="/content/images/1541748926.png">
                    <p class="footer_logo_text">
                    <p>
                        CopyRight 2013 All Right Reserved PHPWEB外贸网站&nbsp;ICP:08118166
                    </p>
                    </p>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 footer_contact">
                    <p>
                        联系人：王女士
                    </p>
                    <p>
                        手机：136 9928 5614
                    </p>
                    <p>
                        电话：020-22043297
                    </p>
                    <p>
                        邮箱：510551@qq.com
                    </p>
                    <p>
                        地址： 河北省保定市唐县
                    </p>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <div class="col-xs-4 col-md-4 footer_menu">
                        <p class="footer_menu_first"><a target="_blank" href="product/class/index.htm">产品中心</a></p>

                        <p><a href="product/class/-115.html" target="_self">产品分类一</a></p>
                        <p><a href="product/class/-74.html" target="_self">产品分类二</a></p>
                        <p><a href="product/class/-124.html" target="_self">产品分类三</a></p>
                    </div>
                    <div class="col-xs-4 col-md-4 footer_menu">
                        <p class="footer_menu_first"><a target="_blank" href="news/class/index.htm">新闻中心</a></p>

                        <p><a href="news/class/-86.html" target="_self">公司新闻</a></p>
                        <p><a href="news/class/-99.html" target="_self">行业新闻</a></p>
                        <p><a href="news/class/-106.html" target="_self">常见问题</a></p>
                    </div>
                    <div class="col-xs-4 col-md-4 footer_menu">
                        <p class="footer_menu_first"><a target="_blank" href="page/html/about.php.htm">关于我们</a></p>

                        <p><a href="page/html/about.php.htm" target="_self">公司简介</a></p>
                        <p><a href="page/html/contact.php.htm" target="_self">联系我们</a></p>
                        <p><a href="page/html/feedback.php.htm" target="_self">留言反馈</a></p>
                        <p><a href="page/html/services.php.htm" target="_self">我们的服务</a></p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <img class="footer_qrcode" src="/content/images/1524472467.jpg">
                    <p class="footer_qrcode_text">手机二维码</p>
                </div>
            </div>
        </div>
    </footer>


    <!--客服面板-->
    <link rel="stylesheet" type="text/css" href="/content/css/online.css" />
    <div id="cmsFloatPanel">
        <div class="ctrolPanel">
            <a class="service" href="#"></a>
            <a class="message" href="#"></a>
            <a class="qrcode" href="#"></a>
            <a class="arrow" title="返回顶部" href="#"></a>
        </div>
        <div class="servicePanel">
            <div class="servicePanel-inner">
                <div class="serviceMsgPanel">
                    <div class="serviceMsgPanel-hd"><a href="#"><span>关闭</span></a></div>
                    <div class="serviceMsgPanel-bd">
                        <!--在线QQ-->
                        <!--在线QQ-->
                        <!--在线MSN-->


                    </div>
                    <div class="serviceMsgPanel-ft"></div>
                </div>
                <div class="arrowPanel">
                    <div class="arrow02"></div>
                </div>
            </div>
        </div>
        <div class="messagePanel">
            <div class="messagePanel-inner">
                <div class="formPanel">

                    <div class="formPanel-bd">
                        <div class="bdsharebuttonbox" style="display: inline-block; float:left;">
                            <a href="#"
                               class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone"
                                                                       title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina"
                                                                                              title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#"
                                                                                                                                                                                                                                                        class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                        </div>
                        <a type="button" class="btn btn-default btn-xs" href="#"
                           style="margin: 12px 0px 0px 10px;">关闭</a>
                    </div>

                </div>
                <div class="arrowPanel">
                    <div class="arrow01"></div>
                    <div class="arrow02"></div>
                </div>
            </div>
        </div>
        <div class="qrcodePanel">
            <div class="qrcodePanel-inner">
                <div class="codePanel">
                    <div class="codePanel-hd">
                        <span style="float:left">用手机扫描二维码</span><a href="#"><span>关闭</span></a>
                    </div>
                    <div class="codePanel-bd">
                        <img src="/content/images/1524472467.jpg" alt="二维码" />
                    </div>
                </div>
                <div class="arrowPanel">
                    <div class="arrow01"></div>
                    <div class="arrow02"></div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/content/js/online.js"></script>
</body>

</html>